---
spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
Gemfile:
  required:
    ':release':
      - gem: github_changelog_generator
        git: https://github.com/github-changelog-generator/github-changelog-generator
